export const GET_SEARCHED_ANIME_LOAD = 'anime/GET_SEARCHED_ANIME_LOAD';
export const GET_SEARCHED_ANIME_SUCCESS = 'anime/GET_SEARCHED_ANIME_SUCCESS';
export const GET_SEARCHED_ANIME_FAIL = 'anime/GET_SEARCHED_ANIME_FAIL';
export const RESET_STATE = 'anime/RESET_STATE';